name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-format:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black Pillow

      - name: Run Black (auto-format)
        run: black .

      - name: Run Pytest
        run: pytest tests/
